dist: xenial
language: python
python:
  - "3.7"
before_install:
  - pip install codecov pytest-cov
script: pytest --disable-pytest-warnings
env:
  - PYTHONPATH=../
after_script:
  - pytest --cov=./
  - codecov